package dd.springboot.demo.dao;

import dd.springboot.demo.models.YkyRole;
import java.util.List;

public interface YkyRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yky_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yky_role
     *
     * @mbg.generated
     */
    int insert(YkyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yky_role
     *
     * @mbg.generated
     */
    YkyRole selectByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yky_role
     *
     * @mbg.generated
     */
    List<YkyRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yky_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YkyRole record);
}