package dd.springboot.demo.dao;

import dd.springboot.demo.models.YkyRoleUser;
import java.util.List;

public interface YkyRoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yky_role_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer urid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yky_role_user
     *
     * @mbg.generated
     */
    int insert(YkyRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yky_role_user
     *
     * @mbg.generated
     */
    YkyRoleUser selectByPrimaryKey(Integer urid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yky_role_user
     *
     * @mbg.generated
     */
    List<YkyRoleUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yky_role_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YkyRoleUser record);
}