package dd.springboot.demo.dao;

import dd.springboot.demo.models.YkyUser;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
public interface YkyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yky_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yky_user
     *
     * @mbg.generated
     */
    int insert(YkyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yky_user
     *
     * @mbg.generated
     */
    YkyUser selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yky_user
     *
     * @mbg.generated
     */
    List<YkyUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yky_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YkyUser record);
}